---
- name: Install Docker
  hosts: all
  become: true  # Run tasks with elevated privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'  # Use this line for Debian/Ubuntu-based systems

    - name: Install required packages
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_pkg_mgr == 'apt'  # Use this line for Debian/Ubuntu-based systems

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: ansible_pkg_mgr == 'apt'  # Use this line for Debian/Ubuntu-based systems

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      when: ansible_pkg_mgr == 'apt'  # Use this line for Debian/Ubuntu-based systems

    - name: Update apt package cache again
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'  # Use this line for Debian/Ubuntu-based systems

    - name: Install Docker
      package:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

